release:
  github:
    owner: chanyipiaomiao
    name: google-authenticator-cli
  name_template: '{{.Tag}}'
  draft: true
builds:
  - main: main.go
    binary: google-authenticator-cli
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: tar.gz
  wrap_in_directory: true
  replacements:
    amd64: 64-bit
    darwin: macos
    linux: linux
  files:
    - LICENSE
    - README.md
  format_overrides:
    - goos: windows
      format: zip